opencode_instances_dir: /var/lib/opencode
opencode_keyvault_name: homelab-bysxdb-kv
opencode_password_secret_template: "opencode-%s-server-password"

opencode_azure_tenant_secret_template: "opencode-%s-sp-tenant-id"
opencode_azure_client_id_secret_template: "opencode-%s-sp-client-id"
opencode_azure_client_secret_template: "opencode-%s-sp-client-secret"
