---
- name: Check if AMA extension is already installed
  ansible.builtin.shell: |
    Get-AzConnectedMachineExtension `
      -ResourceGroupName {{ azure_monitor_resource_group }} `
      -MachineName {{ inventory_hostname }} `
      | Where-Object Name -eq '{{ azure_monitor_extension_name }}' `
      | ConvertTo-Json -Depth 5 -EnumsAsStrings
  args:
    executable: pwsh
  delegate_to: localhost
  become: false
  register: ama_check
  failed_when: false
  changed_when: false

- name: Display AMA extension check result
  ansible.builtin.debug:
    var: ama_check.stdout
  when: ama_check.stdout | length > 0

- name: Install AMA extension on Arc-enabled server
  ansible.builtin.shell: |
    New-AzConnectedMachineExtension `
      -ResourceGroupName {{ azure_monitor_resource_group }} `
      -Location {{ azure_monitor_location }} `
      -MachineName {{ inventory_hostname }} `
      -Name {{ azure_monitor_extension_name }} `
      -ExtensionType {{ azure_monitor_extension_type }} `
      -Publisher {{ azure_monitor_extension_publisher }} `
      -TypeHandlerVersion {{ azure_monitor_extension_version }} `
      | ConvertTo-Json -Depth 5 -EnumsAsStrings
  args:
    executable: pwsh
  delegate_to: localhost
  become: false
  when: ama_check.stdout | length == 0
  register: ama_install

- name: Display AMA extension installation result
  ansible.builtin.debug:
    var: ama_install.stdout
  when: ama_install.changed
