---
- name: Restart time sync
  ansible.builtin.service:
    name: "{{ 'chrony' if (ansible_facts.services.get('chrony.service') | default({})).state == 'running' else 'systemd-timesyncd' }}"
    state: restarted
