---
- name: Restart time sync
  ansible.builtin.service:
    name: "{{ 'chrony' if common_chrony_unit.stat.exists else 'systemd-timesyncd' }}"
    state: restarted
  when: common_chrony_unit.stat.exists or common_timesyncd_unit.stat.exists
