---
docker_dir: /opt/docker

arc_keyvault_name: homelab-bysxdb-kv

cloudflared_token_secret_name: "cloudflared-tunnel-token-{{ inventory_hostname }}"
cloudflared_origin_cert_secret_name: "cloudflared-origin-cert-{{ inventory_hostname }}"
cloudflared_origin_key_secret_name: "cloudflared-origin-key-{{ inventory_hostname }}"
