---
extends: default
rules:
  line-length:
    max: 220
  truthy:
    check-keys: false
  comments:
    require-starting-space: false
    min-spaces-from-content: 1
  comments-indentation: disable
  document-start:
    present: false
  indentation:
    spaces: 2
    indent-sequences: consistent
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
  new-line-at-end-of-file: disable
  new-lines: disable
